-- MySQL Script generated by MySQL Workbench
-- Tue Oct 27 16:06:54 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema testDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema testDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `testDB` DEFAULT CHARACTER SET utf8 ;
USE `testDB` ;

-- -----------------------------------------------------
-- Table `testDB`.`Movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testDB`.`Movies` (
  `movie_title` VARCHAR(45) NOT NULL,
  `release_year` DATE NOT NULL,
  `rating` INT NOT NULL,
  `price` INT NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`movie_title`, `release_year`, `rating`, `price`, `genre`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
